book_file:
    resource: "@BookBundle/Resources/config/routing.yml"
    prefix:   /

book:
    resource: "@BookBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
